GEMINI_API_KEY = "AIzaSyAy0jopkgWB5OsZG4fUkDza_aZ08t_LKQg"
NEO4J_URI = "neo4j+s://385a2f7a.databases.neo4j.io"
NEO4J_USERNAME = "neo4j"
NEO4J_PASSWORD = "jm59-BPF7qsc4bVVSL6PY8QrHP8D7wETg3Ao2xDCns8"
NEO4J_DATABASE = "neo4j"
